# Generated by Django 4.2.16 on 2026-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0005_change_reminded_done_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='affected_system',
            field=models.CharField(choices=[('priority', 'Priority'), ('qv', 'QV'), ('sf', 'SF'), ('kdesk', 'KDESK'), ('servers', 'Servers - Network connectivity'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='change',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20),
        ),
    ]
