# Generated by Django 4.2.16 on 2026-07-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibob_sync', '0010_provisioningrequest_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('provisioning', 'Provisioning'), ('offboarding', 'Offboarding')], max_length=20)),
                ('overall', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('remediated', 'Remediated'), ('escalated', 'Escalated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('checks', models.JSONField(default=list)),
                ('remediations', models.JSONField(default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('diagnosis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offboarding_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='hibob_sync.offboardingrequest')),
                ('provisioning_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='hibob_sync.provisioningrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
