# Generated by Django 4.2.16 on 2026-07-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibob_sync', '0011_verificationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='offboardingrequest',
            name='onedrive_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
