# Generated by Django 4.2.16 on 2026-07-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibob_sync', '0012_offboardingrequest_onedrive_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationresult',
            name='issue_url',
            field=models.URLField(blank=True),
        ),
    ]
