# Generated by Django 4.2.16 on 2026-04-13 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_category_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsubcategory',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Auto-assign tickets to this admin when this sub-category is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
