# Generated by Django 4.2.16 on 2026-04-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_subcategory_assignee_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('pending_user', 'Pending User Reply'), ('pending_vendor', 'Pending Vendor'), ('hold', 'Hold'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
    ]
