# Generated by Django 4.2.16 on 2026-04-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description_is_html',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='content_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='is_inline',
            field=models.BooleanField(default=False),
        ),
    ]
