# Generated by Django 4.2.16 on 2026-04-16 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0012_ticket_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('pending_user', 'Pending User Reply'), ('pending_vendor', 'Pending Vendor'), ('hold', 'Hold'), ('closed', 'Closed'), ('user_responded', 'User Responded')], db_index=True, default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_ticket_emails', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='tickets.ticket')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
