# Generated by Django 4.2.16 on 2026-04-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_satisfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='satisfaction_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
