# Generated by Django 4.2.16 on 2026-05-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_attachment_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('pending_user', 'Pending User Reply'), ('pending_vendor', 'Pending Vendor'), ('hold', 'Hold'), ('pending_manager', 'Pending Manager Approval'), ('closed', 'Closed'), ('user_responded', 'User Responded')], db_index=True, default='new', max_length=20),
        ),
    ]
